honeycombio/libhoney-js

.eslintrc.json
package.json
src/builder.js
src/event.js
src/libhoney.js
src/transmission.js
test/builder_test.js
test/event_test.js
test/libhoney_test.js
test/transmission_test.js

add concurrent batches (serially sending events within a batch) instead of doing one concurrent send per event in the batch.
Before this change we would start sending a batch once one of the triggers (# events/timeout) fired, but we'd make N calls req.send at once.
This change instead works through an individual batch serially, sending one event then the next.
Concurrency is managed by permitting multiple batches to be processed at the same time, up to `maxConcurrentBatches` (default 10.)
also before this change our `eventQueue` could grow without bound if processing events was slow.
This change adds `pendingWorkCapacity` (default 10000) which is the max size of the pending event queue before we start dropping events.
This brings the behavior of the JS SDK a little closer in line with the …

transmission love

---

package.json
src/transmission.js
test/transmission_test.js

The size trigger should activate on >=, not >, so a batchSizeTrigger of N means sending N events will trigger the batch, not N+1.
Ensure that batchSizeTrigger is clamped to >= 1.

Batch size trigger fixes

---

src/libhoney.js
test/libhoney_test.js
test/mock_transmission.js

if `disabled` is `true` we disable the transmission entirely.
libhoney already has the means of disabling hitting the transmission implementation (`this._usable`).  we piggyback off this and have `getAndInitTransmission` return null in the case `options.disable` is true.
Should address #9

add .disabled flag to libhoney constructor options

---

.travis.yml
README.md
package.json
src/libhoney.js

Pairs with https://github.com/honeycombio/www/commit/9e2871341fdc4891d75fb400beaadf198974c662 / Anditi complaining about JS warnings in their console.
Also, when this is fixed, we should really change the instruction to "read the source code" for more info (facepalm) :

Update jsdoc on Libhoney constructor, add esdoc generation to .travis

---

src/event.js
src/libhoney.js

Make sure `.timestamp` is documented as a property on the JS SDK.

Add jsdoc about `.timestamp` on JS docs, factor out validation step

---

src/event.js
test/event_test.js

Groan. `stringify`ing them in the SDK prevents unrolling from being possible on the server. (Going to run through our other SDKs to see whether any of them also do this, cringe)

Stop `stringify`ing JS objects now that we can unroll on the server

---

package.json
src/libhoney.js
src/transmission.js
test/transmission_test.js

pretty simple pair of changes masked with a lot of additional churn.
Adds a class called `BatchEndpointAggregator` to `transmission.js` that groups events based on apiHost/writekey/datasetname.  It does manual JSON encoding to not double encode event post data (which is already `JSON.stringify`ed before making it to transmission)
The `Transmission#_sendBatch` method is where the other part of the change is.  Once a batch of events is chosen (through timeout or event count triggers), it's aggregated.  Then we create a promise to send each batch endpoint aggregated list of events.
The bulk of the test changes are to deal with the fact that with the batch endpoint supported, we get multiple responses at once.

use /1/batch/<dataset> endpoint

---

examples/express-dynamic-fields/express-honey.js

Addresses #17 . It does successfully gets deduped in https://github.com/honeycombio/libhoney-js/blob/master/src/builder.js#L114, but otherwise we shouldn't be... redefining these functions on every request.

Move `addDynamicField` calls out of req handler in `express-dynamic-fields` example`

---

package.json
src/libhoney.js
src/transmission.js
test/transmission_test.js

Follow libhoney-go's lead here and add a special configuration option that lets the user put additional info in the User-Agent string.
For the go sdk we use this to tag integrations, and the same will hold true here.
Also, it's about time we flipped out of beta so people can start getting updates via semver as opposed to explicitly updating to a new beta.

Add support for User-Agent additions

---

src/builder.js
test/builder_test.js
test/event_test.js

`event.addField`/`.add` already work this way, but `builder.addField` does it differently because.. some reason.
Add tests for both events and builders.

don't stringify objects in builder.addField

---

package.json

Hi team Honeycomb 👋 
We ([Snyk](https://snyk.io)) just started checking out Honeycomb, and noticed that the version of superagent used in this lib has a [low-severity vulnerability](https://snyk.io/vuln/npm:superagent:20170807).
This small PR updates superagent to a non-vulnerable version. From the [superagent release notes](https://github.com/visionmedia/superagent/releases/tag/v3.0.0) it looks like biggest potential impact of jumping from 2.x to 3.x is the Node 4+ requirement. I couldn't tell from this repo whether that is going to be an issue for you, so figured I'd raise the PR in any case 😄

Upgrade superagent to remove vulnerability

---

CONTRIBUTORS
README.md

I found these two issues with the ReadMe while I was using libhoney, the documentation doesn't seem to have its own repo so they will so need to be updated to be at parity. 
1) Updated npm installation to have --save instead of --save-dev 
2) Add yarn install to installation

updating readme to include correct npm installation and adding yarn

---

README.md

instead, tell them to generate an api key with event permission only

remove scary text about using us in browser applications

---

package.json
src/__tests__/transmission_test.js
src/libhoney.js
src/transmission.js
yarn.lock

`superagent` makes this really simple, as it happens.  the proxy can be either a string (`https://my-proxy:1234/`) or a map of proxy options (which I didn't look into.)
the added test is just a smoke test - we pass if a connection is made to the proxy server at all.

add a proxy config option

---

src/libhoney.js

I believe this `proxy` option is optional so this fixes the jsdoc syntax

Change proxy jsdoc to optional

---

package.json
yarn.lock

Was unused in the rollup config introducing unnecessary confusion to why
it was included in the dependencies. Verified all scripts defined in
package.json run successfully without it.

Remove rollup-plugin-babel

---

examples/express-dynamic-fields/package.json

Was previously conflicting with another package within the examples/
directory and issuing a warning when running the test suite.

Rename example package name to be unique

---

.travis.yml
README.md
package.json

v9 has been EOL since June 2018. Only versions 6, 8, and 10+ continue to
be supported. Supporting v9 is causing issues with dependent libraries
as seen here: https://travis-ci.org/honeycombio/libhoney-js/jobs/511749577
More info on supported versions here: https://github.com/nodejs/Release
NOTE: Once this is merged, re-running CI on PR #45 will make it pass successfully.

Drop support for unsupported version of node

---

.eslintrc.json
package.json
src/__tests__/builder_test.js
src/__tests__/event_test.js
src/__tests__/libhoney_test.js
src/__tests__/transmission_test.js
src/builder.js
src/event.js
src/libhoney.js
src/transmission.js
yarn.lock

Added a few common linting rules lifted liberally from AirBnB's ESLint config. These help improve readability, and standardise code style throughout the codebase.
The diff is a little messy but viewing each commit individually should make this a little easier to review.

Add more linting rules to improve readability

---

.circleci/config.yml

makes things quite a bit easier to read.  not sure about the docker image names, but we'll see with the PR build.

[circleci] use an executor and job parameters like libhoney-go

---

package.json
src/__tests__/transmission_test.js
src/libhoney.js
src/transmission.js
yarn.lock

Unlike the other libhoney implementations, we can't _actually_ block in this call.  Instead we return a Promise so the user can `await` or `.then` to be signaled once all currently enqueued events/batches are sent and responded to.

add flush() method

---

.circleci/config.yml
README.md
package.json
src/transmission.js
yarn.lock

mostly triggered by a high vuln audit issue on `https-proxy-agent`, but I went ahead and fixed all the other audit issues and bumped most of our deps.
`https-proxy-agent` is a dependency from a lot of other packages all of which are transitive deps for us and some of which don't even specify version 3.0.0, so use a `resolutions` entry for it.

upgrade a lot of deps, drop node v6, fix lint warnings

---

src/libhoney.js

dropping support for node v6 (#57) necessitates a major bump, so let's finally get rid of this hack so support something that hasn't been necessary since we switched to rollup.

drop our funky hack to support the way gulp used to build our cjs module

---

.circleci/config.yml

currently our circleci config attempts to publish for any master commit, which is.. bad.  It should only happen for tags.
I can never remember the branches/tags stuff, so I copied elements of the ruby libhoney/beeline config with the tag regexp tailored to libhoney-js's tags.

stop relying on npm publish not allowing us to overwrite a version

---

.eslintrc.json
package.json
src/transmission.js
yarn.lock

A user report on time required to import `beeline-nodejs` led to this.
using the following file (`time-require.js`):
```
const start = Date.now();
require(process.argv[2]);
const end = Date.now();
console.log(`${end - start} ms`);
```
in a node project where I'd installed beeline-nodejs:
```
toshok-hound:import-test toshok$ node time-require.js honeycomb-beeline
170 ms
toshok-hound:import-test toshok$ node time-require.js libhoney
161 ms
```
digging a little deeper, and it turns out `superagent-proxy` is the biggest culprit:
```
toshok-hound:import-test toshok$ node time-require.js superagent-proxy
133 ms
```
Many (most?) uses of libhoney are not even going to use a proxy, so this PR stops doing a top-level import of `superagent-proxy`, opting for the complexity increasing change here, …

use dynamic import() for superagent-proxy

---

package.json
types/libhoney.d.ts

Add typescript types

---

package.json

I'm sure this was meant as a dev dependency to begin with, so just a small fix.
Fixes:
Annoying warning seen by any honeycomb-beeline user: "warning "honeycomb-beeline > libhoney > babel-eslint@10.1.0" has unmet peer dependency "eslint@>= 4.12.1"."
Reduces honecomb-beeline install by 9.4MB (!)
cc @daiyi

Move babel-eslint to a dev dependency

---

.eslintrc.json
package.json
rollup.browser.config.js
rollup.config.js
src/__tests__/transmission_test.js
src/transmission.js

Some browsers log to the console if JS makes an XHR with a custom `User-Agent` header.  Regardless of the console output, all browsers disallow JS setting it, so at the API we lose version info.
Instead of trying to autodetect, add a `browser` bundle that uses the `X-Honeycomb-UserAgent`, and also removes the `superagent-proxy` import entirely.
Fixes #67 
Fixes #63

fix User-Agent and superagent-proxy issues by building a browser bundle

---

src/__tests__/transmission_test.js
src/libhoney.js
src/transmission.js

Most of the fix for https://github.com/honeycombio/beeline-nodejs/issues/201 (will still need to add the config parameter there as well to pass on to libhoney).
Adds a `timeout` config option to the libhoney (and transmission), and respect it when doing a `POST`.
also clean up the superagent-mocker between tests so we can actually have an unmocked test.  superagent-mocker doesn't allow for async mocks 🤯 so we have to run an actual http server as part of this particular test in order to simulate a timeout.

add a timeout for an entire batch send/response of 60s

---

src/__tests__/builder_test.js
src/__tests__/libhoney_test.js
src/libhoney.js
src/transmission.js

while testing the `writer` transmission for https://github.com/honeycombio/beeline-nodejs/issues/221, I noticed that we're double quoting (as in quoting twice, not using double quotes) the json that we send to stdout.
Rather than stomaching a breaking change, introduce a new transmission implementation called `console`, which will output proper parseable events to the console.
using `writer`:
```
"{\"time\":\"2020-07-10T20:39:53.747Z\",\"samplerate\":1,\"data\":{\"meta.local_hostname\":\"MacBook-Pro-3.local\",\"service_name\":null,\"name\":\"fast-child\",\"trace.trace_id\":\"1de121e83672afcfb8253c03718c9a34\",\"trace.span_id\":\"f98f71ce844e16e2\",\"trace.parent_id\":\"a74e2500137cabbb\",\"duration_ms\":1.666767,\"meta.instrumentations\":[],\"meta.instrumentation_count\":0,\"meta.beeline_v …
```

add "console" transmission implementation which outputs valid parseable JSON event objects.  deprecate "writer" transmission implementation.

---

.circleci/config.yml
README.md

Similar to what was just done for beeline-nodejs:
* Updates to the CircleCI build process so that it more closely matches our "state of the art" process, including:
* Matrix for node versions
* Publish to github releases in addition to npm.
* General cleanup
* Added CHANGELOG.md
* Instructions for using npm version to update the build number.
(Note: The build yellow because I changed the name of the CircleCI check from build-libhoney to build, I will change this in the github configuration as soon as the PR is signed off.)

Modernize circleci, add publish_github

---

src/transmission.js

This allows tools an easier time to pick up on the deprecated parts.

Use doc comment for WriterTransmission deprecation

---

src/__tests__/libhoney_test.js
src/__tests__/transmission_test.js

Looking at https://github.com/honeycombio/libhoney-js/blob/bf545810b604731d48be2e01dee07a039e90cf5d/src/transmission.js#L127 and https://github.com/honeycombio/libhoney-js/blob/bf545810b604731d48be2e01dee07a039e90cf5d/src/libhoney.js#L289 , `postData` is supposed to be an object, not a string. This change fixes the unit tests to match that behaviour and not stringify the `postData` before passing it to `ValidatedEvent`.
There's also a small change around the unstringifyable content, making sure that self-referencing object actually goes into the `postData`.
This also adds a separate change to test libhoney's option to provide a transmission constructor.

Improve transmission unit tests

---

.circleci/config.yml
package.json

- https://github.com/honeycombio/libhoney-js/issues/107
- remove the npm publish step from CI until it's fixed

Bump version - I published 2.2.3 manually as a hotfix

---

.circleci/config.yml

- package entrypoints for libhoney are in the /dist (rollup artifacts)
- need to `yarn build` so they exist when publishing
- see output from a dry run: https://app.circleci.com/pipelines/github/honeycombio/libhoney-js/381/workflows/f8c49d3c-5833-4ddd-b147-6089e3a0a01c/jobs/2144

fix npm publish

---

src/libhoney.js
src/transmission.js

Outputs valid, parseable JSON event objects to stdout. This is especially useful for AWS Lambda environments in concert with the Honeycomb Lambda Extension, as the nodejs Lambda runtime monkeypatches `console.log` with datestamps

add "stdout" transmission implementation

---

.circleci/config.yml

A few changes here:
- switch to [cimg](https://github.com/CircleCI-Public/cimg-overview) for docker images. This supercedes the previous `circleci` images, which don't have an image for node 16.
- `cimg` images don't have tags for just major versions, so specifying latest available minor versions
- dropping node 11 from the matrix because there's no image for it, and odd versions are kind of "temporary" in the node world, until next even version becomes "active": https://nodesource.com/blog/understanding-how-node-js-release-lines-work/

Add node 16 to test matrix

---

package.json

Consumers of libhoney-js should be able to use yarn (fixes #169).

fix: remove yarn from engines

---

package-lock.json

- https://github.com/honeycombio/libhoney-js/security/dependabot/package-lock.json/vm2/open
- updates https://github.com/honeycombio/telemetry-team/issues/163
- https://github.com/patriksimek/vm2/releases
- this only updates the lock file, so not a user-facing change (users could already lock to a safe version)

bump vm2 from 3.9.3 to 3.9.5

---

package.json

- #246 removed pre-commit linting, we don't need the lint-staged script anymore
- YEET

maint: remove unused script

---

package.json
setupTests.js
src/__tests__/libhoney_test.js
src/libhoney.js

- calling `honey.flush()` when `honey` was instantiated with `disabled: true` throws an error
```
TypeError: Cannot read properties of null (reading 'flush')
at Libhoney.flush (/Users/sjchmiela/Developer/luma/node_modules/.pnpm/libhoney@3.1.0/node_modules/libhoney/dist/libhoney.cjs.js:1400:25)
at null.runJob (/Users/sjchmiela/Developer/luma/server/src/services/job-runner.ts:98:17)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
- `transmission` may be `null` if `options.disabled` is true, as per https://github.com/honeycombio/libhoney-js/blob/177a17bcb311ea6988f3e0ebd24e15b4f316d3a9/src/libhoney.js#L493-L496 — we should check if `transmission` exists before calling `.flush` on it.

Handle `null` transmission in `flush`

---

src/__tests__/transmission_test.js

- Cleans up two tests so that jest doesn't complain that some tests were failing to close sockets
- Destroy a socket rather than close it because the socket was waiting for an acknowledgement that would never come
- Adjust timeout so that server closes before jest gets bored
- Call done() from within close() so that it has time to close.
Note that the standard formatting has changed a bit in the last 4 years, so this includes some whitespace changes due to eslint.
@jessitron contributed a lot to figuring this out.

Update tests to properly terminate

---

.circleci/config.yml

- node 18 has been out since April 😁 
- test node 18 in CI
- also update default version to one that's in maintenance LTS

maint: add node 18 to CI matrix

---

src/__tests__/transmission_test.js
src/transmission.js

- closes https://github.com/honeycombio/libhoney-js/issues/298
- Add node version to user-agent header. 
- Test expected versions are in the header and that it is in the correct order

Add node/version to the user agent header.

---

.circleci/config.yml

- bump CircleCI to only test latest node v14, v16, v18 (current security supported node versions)
- Set circleCI default to latest v16 (14 is in process of EOL in the next several months)

Set circleCI node default to latest v16; bump node version matrix to latest minor releases

---

CHANGELOG.md
RELEASE.md
package-lock.json
package.json

- Drop Node v12, no longer security supported (#308)
- Set circleCI Node default to latest v16 (#310)
also added cli commands to release.md for easy reference, similar to libhoney-py.

[release] Prepare 4.4.0 - Drop Node 12 Support

---

babel.config.js
package-lock.json
package.json
src/transmission.js

libhoney is pulling in a helper library called urljoin to fuse URL components together. urljoin expects to be run in a Node environment, and uses the Node standard library (notably the path module). Because of this dependency, libhoney fails for us when run under Webpack 5, which no longer bundles Node libraries in.
This PR swaps urljoin out for an alternative library with equivalent functionality, called url-join. url-join has no dependencies, and is newer than urljoin and still maintained.
Because it's new, it uses ES Modules; I needed to configure Jest to use Babel to transform it.

fix: Use url-join instead of urljoin

---

package-lock.json
package.json
rollup.browser.config.js
rollup.config.js
src/transmission.js

- Resolves #380 
This is the equivalent behavior of the previous agent configuration. If a proxy URL is provided in libhoney config, a single ProxyAgent will be created with that proxy URL set for all connections. No nuanced lookup of proxy config from the environment based on target URL protocol.
[proxy-agent is a hefty import](https://bundlephobia.com/package/proxy-agent@6.3.0), but we were importing an early edition of it ([v5.0.0](https://bundlephobia.com/package/proxy-agent@5.0.0)) already via superagent-proxy. Update: whew, bundlephobia really doesn't handle direct links well.
- updates to **rollup** configs

fix: replace superagent-proxy with direct use of proxy-agent

---

docker-compose.yml
examples/express/app.js
examples/express/express-honey.js
src/__tests__/transmission_test.js

- adding a bit more confidence in unit testing for proxy usage as a follow-up from #389 
- extra test that confirms http headers and method are passed along to the proxy server
- optional: added docker-compose for easy spinning up of proxies, along with some extra attributes for event if the proxy is in use.

maint: extra test to check for http info from proxy

---

src/__tests__/libhoney_test.js
src/libhoney.js

We've released Ingest Keys, but need to update the key detection logic to allow Ingest Keys to be used to send data to Classic environments.
- updates the Classic API Key detection logic to understand the shape of a Classic Ingest Key
- Changes `isClassic` from a "private" class method of `Libhoney` to a static class method, so we can reuse it in dependent libraries without repeating logic everywhere

feat: support classic ingest keys

---

CHANGELOG.md
README.md
package-lock.json
package.json

Prepares the next release of libhoney-js.
- Update version to 4.3.0
- Add changelog entry
- Update README with updated Node version (14.18)
- Update min node version in package.json

rel: Prepare v4.3.0 release
